### ISSUE TITLE
Add a Free and Open Source License to Scotch Box Pro

### ISSUE THREAD

**Issue by DavidGinzberg** [scotch-io/scotch-box-pro#27]
Given that Scotch Box appears to no longer be receiving updates, and Scotch.io has announced they are closing, please consider explicitly adding a FOSS-compatible license to the relevant repos (Scotch Box Free, Scotch Box Pro, the builder scripts, and the nginx varations) so that anyone still interested in using it can feel comfortable repackaging and updating. I'd be happy to put a little time into updating it for 2021 and posting the corresponding build scripts and boxes if there's still interest out there.

**Comment by m0lmk** [comment]
I fully support this. I'm a pro user and this would be a great thing to do as a final farewell.

**Comment by whatnickcodes** [comment]
https://github.com/scotch-io/scotch-box-build-scripts
https://github.com/scotch-io/scotch-box
https://github.com/scotch-io/scotch-box-pro
https://github.com/scotch-io/scotch-box-pro-nginx

**Comment by DavidGinzberg** [comment]
Seems like a good choice to me. Plenty permissive with a share-alike requirement.
